name: Run tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ['1.6', '1', 'nightly']
        julia-arch: [x64, x86]
        os: [ubuntu-latest]
        include:
          - os: macOS-latest
            julia-arch: x64
            julia-version: nightly
          - os: windows-latest
            julia-arch: x64
            julia-version: nightly
          - os: windows-latest
            julia-arch: x86
            julia-version: nightly

    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      - uses: julia-actions/julia-buildpkg@latest
      - uses: julia-actions/julia-runtest@latest
